"""Initial knowledge schema: entities, edges, provenance and the review pipeline.

Revision ID: 0001
Revises:
Create Date: 2026-09-21
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("normalized_name", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('skill', 'project', 'organization', 'role', 'education', 'credential', 'achievement', 'responsibility')",
            name=op.f("ck_entity_kind"),
        ),
        sa.CheckConstraint(
            "state IN ('confirmed', 'learning', 'gap', 'archived')", name=op.f("ck_entity_state")
        ),
        sa.CheckConstraint("length(name) > 0", name=op.f("ck_entity_name_not_empty")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity")),
    )
    with op.batch_alter_table("entity", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_entity_normalized_name"), ["normalized_name"], unique=False
        )

    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("uri", sa.String(), nullable=True),
        sa.Column("content_hash", sa.String(), nullable=True),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.Column("raw_text_path", sa.String(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('conversation', 'document', 'web', 'manual')", name=op.f("ck_source_kind")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
    )
    op.create_table(
        "achievement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("metric", sa.String(), nullable=True),
        sa.Column("value", sa.String(), nullable=True),
        sa.Column("occurred_at", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"], ["entity.id"], name=op.f("fk_achievement_id_entity"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_achievement")),
    )
    op.create_table(
        "credential",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("credential_type", sa.String(), nullable=True),
        sa.Column("issued_at", sa.Date(), nullable=True),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.Column("credential_id", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.CheckConstraint(
            "credential_type IS NULL OR credential_type IN ('certification', 'course', 'bootcamp')",
            name=op.f("ck_credential_credential_type"),
        ),
        sa.CheckConstraint(
            "issued_at IS NULL OR expires_at IS NULL OR expires_at >= issued_at",
            name=op.f("ck_credential_dates_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["entity.id"], name=op.f("fk_credential_id_entity"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_credential")),
    )
    op.create_table(
        "edge",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("src_id", sa.Integer(), nullable=False),
        sa.Column("rel", sa.String(), nullable=False),
        sa.Column("dst_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("started_at", sa.Date(), nullable=True),
        sa.Column("ended_at", sa.Date(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.CheckConstraint(
            "rel IN ('used_in', 'at_organization', 'produced', 'involved', 'demonstrates', 'taught_by', 'part_of', 'related_to')",
            name=op.f("ck_edge_rel"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_edge_confidence_range"),
        ),
        sa.CheckConstraint("src_id != dst_id", name=op.f("ck_edge_no_self_loop")),
        sa.CheckConstraint(
            "started_at IS NULL OR ended_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_edge_dates_ordered"),
        ),
        sa.ForeignKeyConstraint(["dst_id"], ["entity.id"], name=op.f("fk_edge_dst_id_entity")),
        sa.ForeignKeyConstraint(["src_id"], ["entity.id"], name=op.f("fk_edge_src_id_entity")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_edge")),
        sa.UniqueConstraint("src_id", "rel", "dst_id", name=op.f("uq_edge_src_id_rel_dst_id")),
    )
    op.create_table(
        "education",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("degree", sa.String(), nullable=True),
        sa.Column("field", sa.String(), nullable=True),
        sa.Column("started_at", sa.Date(), nullable=True),
        sa.Column("ended_at", sa.Date(), nullable=True),
        sa.Column("grade", sa.String(), nullable=True),
        sa.CheckConstraint(
            "started_at IS NULL OR ended_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_education_dates_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["entity.id"], name=op.f("fk_education_id_entity"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_education")),
    )
    op.create_table(
        "evidence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("locator", sa.String(), nullable=False),
        sa.Column("excerpt", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name=op.f("fk_evidence_source_id_source")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    op.create_table(
        "organization",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("org_type", sa.String(), nullable=True),
        sa.Column("industry", sa.String(), nullable=True),
        sa.Column("size", sa.String(), nullable=True),
        sa.CheckConstraint(
            "org_type IS NULL OR org_type IN ('employer', 'client', 'institution')",
            name=op.f("ck_organization_org_type"),
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["entity.id"], name=op.f("fk_organization_id_entity"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization")),
    )
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.Date(), nullable=True),
        sa.Column("ended_at", sa.Date(), nullable=True),
        sa.Column("context", sa.String(), nullable=True),
        sa.CheckConstraint(
            "started_at IS NULL OR ended_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_project_dates_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["entity.id"], name=op.f("fk_project_id_entity"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project")),
    )
    op.create_table(
        "proposal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "origin IN ('chat', 'document', 'interview', 'web')", name=op.f("ck_proposal_origin")
        ),
        sa.CheckConstraint("status IN ('open', 'committed')", name=op.f("ck_proposal_status")),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name=op.f("fk_proposal_source_id_source")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposal")),
    )
    op.create_table(
        "responsibility",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scope", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id"], ["entity.id"], name=op.f("fk_responsibility_id_entity"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_responsibility")),
    )
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("seniority", sa.String(), nullable=True),
        sa.Column("started_at", sa.Date(), nullable=True),
        sa.Column("ended_at", sa.Date(), nullable=True),
        sa.Column("employment_type", sa.String(), nullable=True),
        sa.CheckConstraint(
            "started_at IS NULL OR ended_at IS NULL OR ended_at >= started_at",
            name=op.f("ck_role_dates_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["entity.id"], name=op.f("fk_role_id_entity"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
    )
    op.create_table(
        "skill",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.CheckConstraint(
            "category IS NULL OR category IN ('language', 'framework', 'tool', 'platform', 'method', 'soft')",
            name=op.f("ck_skill_category"),
        ),
        sa.ForeignKeyConstraint(
            ["id"], ["entity.id"], name=op.f("fk_skill_id_entity"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill")),
    )
    op.create_table(
        "assertion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_kind", sa.String(), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("field", sa.String(), nullable=True),
        sa.Column("value_json", sa.JSON(), nullable=True),
        sa.Column("evidence_id", sa.Integer(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "target_kind IN ('entity', 'edge')", name=op.f("ck_assertion_target_kind")
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"], ["evidence.id"], name=op.f("fk_assertion_evidence_id_evidence")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assertion")),
    )
    with op.batch_alter_table("assertion", schema=None) as batch_op:
        batch_op.create_index("ix_assertion_target", ["target_kind", "target_id"], unique=False)

    op.create_table(
        "commit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("applied_at", sa.DateTime(), nullable=False),
        sa.Column("operation_ids_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["proposal_id"], ["proposal.id"], name=op.f("fk_commit_log_proposal_id_proposal")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commit_log")),
    )
    op.create_table(
        "operation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("proposal_id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("op_type", sa.String(), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("classification", sa.String(), nullable=False),
        sa.Column("target_kind", sa.String(), nullable=True),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("edited_payload_json", sa.JSON(), nullable=True),
        sa.Column("rationale", sa.String(), nullable=True),
        sa.CheckConstraint(
            "(classification = 'new' AND target_id IS NULL AND target_kind IS NULL) OR (classification != 'new' AND target_id IS NOT NULL AND target_kind IS NOT NULL)",
            name=op.f("ck_operation_target_matches_classification"),
        ),
        sa.CheckConstraint(
            "classification IN ('new', 'known', 'duplicate', 'conflict')",
            name=op.f("ck_operation_classification"),
        ),
        sa.CheckConstraint(
            "op_type IN ('create_entity', 'update_field', 'add_edge', 'attach_evidence', 'merge_duplicate', 'set_state')",
            name=op.f("ck_operation_op_type"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'edited', 'rejected', 'applied')",
            name=op.f("ck_operation_status"),
        ),
        sa.CheckConstraint(
            "target_kind IS NULL OR target_kind IN ('entity', 'edge')",
            name=op.f("ck_operation_target_kind"),
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"], ["proposal.id"], name=op.f("fk_operation_proposal_id_proposal")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation")),
        sa.UniqueConstraint("proposal_id", "seq", name=op.f("uq_operation_proposal_id_seq")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("operation")
    op.drop_table("commit_log")
    with op.batch_alter_table("assertion", schema=None) as batch_op:
        batch_op.drop_index("ix_assertion_target")

    op.drop_table("assertion")
    op.drop_table("skill")
    op.drop_table("role")
    op.drop_table("responsibility")
    op.drop_table("proposal")
    op.drop_table("project")
    op.drop_table("organization")
    op.drop_table("evidence")
    op.drop_table("education")
    op.drop_table("edge")
    op.drop_table("credential")
    op.drop_table("achievement")
    op.drop_table("source")
    with op.batch_alter_table("entity", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entity_normalized_name"))

    op.drop_table("entity")
    # ### end Alembic commands ###
