"""Add the app_setting table and two non-blank CHECK constraints on evidence.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-27 10:48:02.136189
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # `compare_metadata` does not compare CHECK constraints, so autogenerate never
    # saw these; hand-added, and held by
    # test_the_migrated_check_constraints_match_the_declared_ones (audit F5).
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_check_constraint("locator_nonblank", "length(trim(locator)) > 0")
        batch_op.create_check_constraint("excerpt_nonblank", "length(trim(excerpt)) > 0")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_setting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("base_url", sa.String(), nullable=True),
        sa.Column("api_key_env", sa.String(), nullable=True),
        sa.Column("allow_external", sa.Boolean(), nullable=False),
        sa.Column("embedding_provider", sa.String(), nullable=False),
        sa.Column("embedding_model", sa.String(), nullable=False),
        sa.Column("similarity_threshold", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "provider IN ('ollama', 'anthropic', 'openai')", name=op.f("ck_app_setting_provider")
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_app_setting_single_row")),
        sa.CheckConstraint(
            "similarity_threshold >= 0 AND similarity_threshold <= 1",
            name=op.f("ck_app_setting_similarity_threshold_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_setting")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_setting")
    # ### end Alembic commands ###

    with op.batch_alter_table("evidence", schema=None) as batch_op:
        # Bare names, like create_check_constraint above: batch mode applies the
        # naming convention itself, and the fully-formatted name here would double it.
        batch_op.drop_constraint("excerpt_nonblank", type_="check")
        batch_op.drop_constraint("locator_nonblank", type_="check")
