/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Message
         * @description Store a message, extract facts from it, and record them as a pending proposal.
         *
         *     The message is written as provenance before the model runs; a model failure
         *     afterwards leaves the message and no proposal.
         *
         *     Args:
         *         db: The knowledge-base engine.
         *         body: The message.
         *         embedder: Used for similarity, if configured.
         *         model_factory: Builds the model for this request.
         *
         *     Returns:
         *         The reply, the pending proposal and anything the agent produced that was dropped.
         *
         *     Raises:
         *         HTTPException: 404 for an unknown conversation; 502 if the model fails.
         */
        post: operations["post_message_api_chat_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/messages/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Message Stream
         * @description Like `post_message`, but streams the reply as NDJSON (FR-13).
         *
         *     Events, one JSON object per line: `delta` (growth of the reply), `proposal`
         *     (the stored proposal, rejected items and ids), `done`; or `error`, after which
         *     the stream ends. Streaming does not retry an invalid final output: it is an
         *     `error` event (ADR-0014). Size and conversation checks happen before the stream
         *     starts, so they are ordinary 422/404 responses.
         *
         *     Args:
         *         db: The knowledge-base engine.
         *         body: The message.
         *         embedder: Used for similarity, if configured.
         *         model_factory: Builds the model for this request.
         *
         *     Returns:
         *         An `application/x-ndjson` stream.
         */
        post: operations["post_message_stream_api_chat_messages_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Entities
         * @description List entities, optionally filtered by kind and knowledge state.
         *
         *     Args:
         *         conn: Read connection.
         *         kind: Only this kind.
         *         state: Only this knowledge state.
         *
         *     Returns:
         *         Matching entities.
         */
        get: operations["list_entities_api_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entity
         * @description Return one entity with its kind-specific attributes.
         *
         *     Args:
         *         conn: Read connection.
         *         entity_id: The entity id.
         *
         *     Returns:
         *         The entity.
         *
         *     Raises:
         *         HTTPException: 404 if it does not exist.
         */
        get: operations["get_entity_api_entities__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{entity_id}/edges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entity Edges
         * @description Return every edge touching an entity.
         *
         *     Args:
         *         conn: Read connection.
         *         entity_id: The entity id.
         *
         *     Returns:
         *         The edges.
         */
        get: operations["entity_edges_api_entities__entity_id__edges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/{evidence_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Evidence
         * @description Return an evidence span's literal excerpt and its source (FR-03).
         *
         *     Args:
         *         conn: Read connection.
         *         evidence_id: The evidence id an operation payload carries.
         *
         *     Returns:
         *         The evidence record.
         *
         *     Raises:
         *         HTTPException: 404 if the evidence does not exist.
         */
        get: operations["get_evidence_api_evidence__evidence_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Report that the process is serving, and which version is running.
         *
         *     Returns:
         *         The liveness payload.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Proposals
         * @description List proposals newest first, each with its pending-operation count.
         *
         *     Args:
         *         conn: Read connection.
         *         status: ``open`` or ``committed``; omit for all.
         *
         *     Returns:
         *         The proposal summaries.
         */
        get: operations["list_proposals_api_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Proposal
         * @description Return a proposal and its operations.
         *
         *     Args:
         *         conn: Read connection.
         *         proposal_id: The proposal id.
         *
         *     Returns:
         *         The proposal.
         *
         *     Raises:
         *         HTTPException: 404 if the proposal does not exist.
         */
        get: operations["get_proposal_api_proposals__proposal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit
         * @description Apply the accepted and edited operations in one transaction.
         *
         *     New entities, and existing ones whose name or summary just changed, are
         *     indexed for similarity search right after (never inside the write
         *     transaction — D-D). A failed embedding call never fails the commit: the
         *     affected ids come back as `index_pending` instead.
         *
         *     Args:
         *         db: The engine.
         *         embedder: What indexes new and changed entities; `None` skips indexing.
         *         proposal_id: The proposal.
         *
         *     Returns:
         *         What was written.
         *
         *     Raises:
         *         NotFoundError: Mapped to 404 if the proposal, or a target an operation
         *             names, does not exist.
         *         ProposalNotOpenError: Mapped to 409 if the proposal was already committed.
         *         OperationsPendingError: Mapped to 409 if any operation is still pending.
         *         UnsupportedOperationError: Mapped to 422 if an operation cannot be
         *             applied by this version (`merge_duplicate`, until M1b).
         *         sqlalchemy.exc.IntegrityError: Mapped to 409; the database rejected a
         *             row and nothing was written.
         */
        post: operations["commit_api_proposals__proposal_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/operations/{operation_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review
         * @description Accept, edit or reject one operation; its siblings are untouched.
         *
         *     Args:
         *         db: The engine. The decision is written through `kb.apply`.
         *         proposal_id: The proposal the operation must belong to.
         *         operation_id: The operation.
         *         body: The decision.
         *
         *     Returns:
         *         The proposal after the decision.
         *
         *     Raises:
         *         HTTPException: 404 if the operation is not part of this proposal.
         *         NotFoundError: Mapped to 404 if the operation does not exist.
         *         ProposalNotOpenError: Mapped to 409 if the proposal was already committed.
         *         InvalidEditError: Mapped to 422 if an edit is missing, changes the
         *             operation type, does not validate, or accompanies accept/reject.
         */
        post: operations["review_api_proposals__proposal_id__operations__operation_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/provenance/{target_kind}/{target_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Provenance
         * @description Show where a stored fact came from: source kind, locator and excerpt (FR-03).
         *
         *     Args:
         *         conn: Read connection.
         *         target_kind: ``entity`` or ``edge``.
         *         target_id: Its id.
         *
         *     Returns:
         *         One record per assertion.
         *
         *     Raises:
         *         HTTPException: 404 if nothing is asserted about that target.
         */
        get: operations["provenance_api_provenance__target_kind___target_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Return the currently persisted provider settings.
         *
         *     Args:
         *         db: The knowledge-base engine.
         *
         *     Returns:
         *         The settings.
         */
        get: operations["get_settings_api_settings_get"];
        /**
         * Put Settings
         * @description Replace the persisted provider settings.
         *
         *     Args:
         *         db: The knowledge-base engine.
         *         body: The full replacement settings.
         *
         *     Returns:
         *         The settings, as persisted.
         *
         *     Raises:
         *         HTTPException: 422 if `body` selects Anthropic or OpenAI without
         *             `allow_external` (NFR-01).
         */
        put: operations["put_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatRequest
         * @description One user message. The text is stored literally, not trimmed.
         *
         *     Attributes:
         *         conversation_id: An existing conversation to continue; a new one when omitted.
         *         text: The message, 1 to 20 000 characters, not blank.
         */
        ChatRequest: {
            /** Conversation Id */
            conversation_id?: number | null;
            /** Text */
            text: string;
        };
        /**
         * ChatResponse
         * @description What the user sees after sending a message.
         *
         *     Attributes:
         *         conversation_id: The conversation (a `source` id) the message belongs to.
         *         message_id: The evidence id of the stored message.
         *         reply: The agent's acknowledgement.
         *         proposal: The pending proposal, if any.
         *         rejected: Agent output that was dropped, and why.
         *         similarity_available: False when duplicate detection could not run.
         */
        ChatResponse: {
            /** Conversation Id */
            conversation_id: number;
            /** Message Id */
            message_id: number;
            proposal: components["schemas"]["ProposalView"];
            /** Rejected */
            rejected: components["schemas"]["RejectedView"][];
            /** Reply */
            reply: string;
            /** Similarity Available */
            similarity_available: boolean;
        };
        /**
         * Committed
         * @description What a commit wrote.
         *
         *     Attributes:
         *         commit_id: The `commit_log` row.
         *         applied_operation_ids: Applied operations, in order.
         *         entity_ids: For each applied `create_entity` seq, the entity it resolved to.
         *         index_pending: Entity ids the similarity index could not embed yet (the
         *             embedder was unavailable). The commit still happened; only the
         *             search index is behind — `reindex_missing` catches these up later.
         */
        Committed: {
            /** Applied Operation Ids */
            applied_operation_ids: number[];
            /** Commit Id */
            commit_id: number;
            /** Entity Ids */
            entity_ids: {
                [key: string]: number;
            };
            /**
             * Index Pending
             * @default []
             */
            index_pending: number[];
        };
        /**
         * EdgeRecord
         * @description One typed relationship.
         */
        EdgeRecord: {
            /** Confidence */
            confidence: number | null;
            /** Dst Id */
            dst_id: number;
            /** Ended At */
            ended_at: unknown;
            /** Id */
            id: number;
            /** Note */
            note: string | null;
            /** Rel */
            rel: string;
            /** Src Id */
            src_id: number;
            /** Started At */
            started_at: unknown;
        };
        /**
         * EntityKind
         * @description The eight entity kinds (spec §4.1).
         * @enum {string}
         */
        EntityKind: "skill" | "project" | "organization" | "role" | "education" | "credential" | "achievement" | "responsibility";
        /**
         * EntityRecord
         * @description One entity with its kind-specific attributes.
         */
        EntityRecord: {
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            };
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Id */
            id: number;
            kind: components["schemas"]["EntityKind"];
            /** Name */
            name: string;
            /** Normalized Name */
            normalized_name: string;
            state: components["schemas"]["KnowledgeState"];
            /** Summary */
            summary: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * EvidenceRecord
         * @description One evidence span resolved to its source.
         *
         *     Attributes:
         *         id: The evidence id.
         *         source_id: The source it was cut from.
         *         source_kind: The source's kind.
         *         source_label: The source's human label.
         *         locator: Where in the source the span sits.
         *         excerpt: The literal text of the span.
         */
        EvidenceRecord: {
            /** Excerpt */
            excerpt: string;
            /** Id */
            id: number;
            /** Locator */
            locator: string;
            /** Source Id */
            source_id: number;
            /** Source Kind */
            source_kind: string;
            /** Source Label */
            source_label: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Health
         * @description Liveness payload.
         *
         *     Attributes:
         *         status: Always `ok` when the process is serving.
         *         version: The running `cvforge` package version.
         */
        Health: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        JsonValue: unknown;
        /**
         * KnowledgeState
         * @description Knowledge state of an entity (spec §4.4). Not a match verdict.
         * @enum {string}
         */
        KnowledgeState: "confirmed" | "learning" | "gap" | "archived";
        /**
         * OperationRecord
         * @description One operation of a proposal, with its review state.
         */
        OperationRecord: {
            /** Classification */
            classification: string;
            /** Edited Payload */
            edited_payload: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: number;
            /** Op Type */
            op_type: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Rationale */
            rationale: string | null;
            /** Seq */
            seq: number;
            /** Status */
            status: string;
            /** Target Id */
            target_id: number | null;
            /** Target Kind */
            target_kind: string | null;
        };
        /**
         * ProposalRecord
         * @description A proposal and its operations in `seq` order.
         */
        ProposalRecord: {
            /** Applied At */
            applied_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Operations */
            operations: components["schemas"]["OperationRecord"][];
            /** Origin */
            origin: string;
            /** Source Id */
            source_id: number;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
        };
        /**
         * ProposalStatus
         * @description Lifecycle of a proposal: open for review, then committed exactly once.
         * @enum {string}
         */
        ProposalStatus: "open" | "committed";
        /**
         * ProposalSummary
         * @description A proposal as a row in the review queue, without its operations.
         *
         *     Attributes:
         *         id: The proposal id.
         *         origin: Which flow produced it (``chat``, ``document``, ...).
         *         status: ``open`` or ``committed``.
         *         summary: The agent's one-line description.
         *         created_at: When it was recorded.
         *         applied_at: When it was committed, or None while open.
         *         operation_count: How many operations it holds.
         *         pending_count: How many of them still await a decision.
         */
        ProposalSummary: {
            /** Applied At */
            applied_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Operation Count */
            operation_count: number;
            /** Origin */
            origin: string;
            /** Pending Count */
            pending_count: number;
            /** Status */
            status: string;
            /** Summary */
            summary: string;
        };
        /**
         * ProposalView
         * @description The proposal a message produced; `id` is None when it produced nothing.
         */
        ProposalView: {
            /** Id */
            id: number | null;
            /** Operations */
            operations: components["schemas"]["ProposedOperation"][];
        };
        /**
         * ProposedOperation
         * @description One pending operation of the stored proposal.
         *
         *     Attributes:
         *         id: The operation id, as used by the review endpoints.
         *         seq: Its position in the proposal.
         *         op_type: The operation type.
         *         payload: The typed payload as stored.
         *         classification: `new`, `known`, `duplicate` or `conflict`.
         *         target_kind: What it refers to, unless `new`.
         *         target_id: The id of that target, unless `new`.
         */
        ProposedOperation: {
            /** Classification */
            classification: string;
            /** Id */
            id: number;
            /** Op Type */
            op_type: string;
            payload: components["schemas"]["JsonValue"];
            /** Seq */
            seq: number;
            /** Target Id */
            target_id: number | null;
            /** Target Kind */
            target_kind: string | null;
        };
        /**
         * ProvenanceRecord
         * @description One assertion resolved back to the literal evidence it cites (FR-03).
         */
        ProvenanceRecord: {
            /** Assertion Id */
            assertion_id: number;
            /** Excerpt */
            excerpt: string;
            /** Field */
            field: string | null;
            /** Locator */
            locator: string;
            /** Source Id */
            source_id: number;
            /** Source Kind */
            source_kind: string;
            /** Source Label */
            source_label: string;
            /** Value */
            value: unknown;
        };
        /**
         * Provider
         * @description LLM providers `build_model()` can construct (spec §5, §2 D5). Local-first: see NFR-01.
         * @enum {string}
         */
        Provider: "ollama" | "anthropic" | "openai";
        /**
         * ProviderSettings
         * @description The persisted, runtime-changeable configuration `build_model()` reads (FR-38, FR-39).
         *
         *     Attributes:
         *         provider: Which LLM provider to build.
         *         model: The provider's model name.
         *         base_url: The provider's endpoint. Only meaningful for `ollama`.
         *         api_key_env: The NAME of an environment variable holding the API key —
         *             never the key itself (ADR-0012 decision D-B). `None` for `ollama`.
         *         allow_external: Must be `True` before `provider` may be `anthropic` or
         *             `openai` (NFR-01).
         *         embedding_provider: Which embedding backend to use. Only `"ollama"`
         *             exists in M1; a real pluggable interface arrives in M1b task B2.1.
         *         embedding_model: The embedding provider's model name.
         *         similarity_threshold: Minimum cosine similarity for a `duplicate` match
         *             (ADR-0012 decision D-G).
         */
        ProviderSettings: {
            /**
             * Allow External
             * @default false
             */
            allow_external: boolean;
            /** Api Key Env */
            api_key_env?: string | null;
            /**
             * Base Url
             * @default http://127.0.0.1:11434
             */
            base_url: string | null;
            /**
             * Embedding Model
             * @default nomic-embed-text
             */
            embedding_model: string;
            /**
             * Embedding Provider
             * @default ollama
             */
            embedding_provider: string;
            /**
             * Model
             * @default qwen3.6:27b
             */
            model: string;
            /** @default ollama */
            provider: components["schemas"]["Provider"];
            /**
             * Similarity Threshold
             * @default 0.85
             */
            similarity_threshold: number;
        };
        /**
         * RejectedView
         * @description Something the agent produced that could not become an operation.
         */
        RejectedView: {
            /** Item */
            item: string;
            /** Reason */
            reason: string;
        };
        /**
         * Review
         * @description A reviewer's decision on one operation.
         *
         *     Attributes:
         *         decision: ``accept``, ``edit`` or ``reject``.
         *         edited_payload: The replacement payload, for ``edit`` only.
         */
        Review: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "accept" | "edit" | "reject";
            /** Edited Payload */
            edited_payload?: {
                [key: string]: components["schemas"]["JsonValue"];
            } | null;
        };
        /**
         * SettingsView
         * @description The persisted settings, plus whether a usable key is configured — never the key itself.
         *
         *     Attributes:
         *         settings: The persisted provider settings.
         *         api_key_configured: True when `settings.api_key_env` names a real,
         *             currently-set environment variable. False both when no name is
         *             set and when the named variable is unset — a caller who only
         *             wants "is a key needed and missing" reads this one field either way.
         */
        SettingsView: {
            /** Api Key Configured */
            api_key_configured: boolean;
            settings: components["schemas"]["ProviderSettings"];
        };
        /**
         * TargetKind
         * @description What an assertion or a classification points at.
         * @enum {string}
         */
        TargetKind: "entity" | "edge";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_message_api_chat_messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_stream_api_chat_messages_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entities_api_entities_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["EntityKind"] | null;
                state?: components["schemas"]["KnowledgeState"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_api_entities__entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_edges_api_entities__entity_id__edges_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EdgeRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_evidence_api_evidence__evidence_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidence_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_proposals_api_proposals_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProposalStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proposal_api_proposals__proposal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_api_proposals__proposal_id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Committed"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_proposals__proposal_id__operations__operation_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
                operation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Review"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provenance_api_provenance__target_kind___target_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_kind: components["schemas"]["TargetKind"];
                target_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvenanceRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
        };
    };
    put_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderSettings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
